### ISSUE TITLE
RECORD_AUDIO permission denied

### ISSUE THREAD

**Issue by jdshkolnik** [jg439/FirstAIAPIApp#1]
Hi @jg439,

I've passed this to a friend at Google and he's agreed to take a look at it.

**Comment by jg439** [comment]
Thank you @jdshkolnik!! have a good day

**Comment by davidzzzz** [comment]
Sorry I'm new to github flow. I've created a pull request which should fix the issue.

The reason is https://developer.android.com/training/permissions/requesting.html.
"Beginning in Android 6.0 (API level 23), users grant permissions to apps while the app is running, not when they install the app." This means for Android M and above, users might not have granted the permissions when they're needed.(You can see the required permissions at settings->apps-><your app>->permissions). Therefore we need to explicitly add the checks.
